force-app/main/default/objects/Member__mdt/Member__mdt.object-meta.xml
<CustomObject>
    <label>Member</label>
    <pluralLabel>Members</pluralLabel>
</CustomObject>

force-app/main/default/objects/Member__mdt/fields/Field_Displayed__c.field-meta.xml
<CustomField>
    <fullName>Field_Displayed__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Field Displayed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Member__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <label>Field Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Member__mdt/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <label>Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>boolean</fullName>
                <default>true</default>
                <label>boolean</label>
            </value>
            <value>
                <fullName>text</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoyaltyMembersController.cls
public with sharing class LoyaltyMembersController {
    
    /* Method: getMembers
     * Description: Calls service to get all Members in loyalty program. 
     * Then builds the member wrapper class to display
     */
    @AuraEnabled
    public static List<Member> getMembers() {
        String results = LoyaltyService.getMembers();
        List<Member> memberList = new List<Member>();
        system.debug('results $$ ' + results);
        memberList = LoyaltyUtility.buildMemberList(results);
        system.debug('memberlist $$ ' + memberList);
        return memberList;
        
    }

    @AuraEnabled
    public static List<Member.MemberColumn> getMemberColumns() {
        List<Member__mdt> mdtList = LoyaltyUtility.getMemberMetadata();
        List<Member.MemberColumn> memberColumns = new List<Member.MemberColumn>();
        for (Member__mdt mdt : mdtList) 
        {
            if (mdt.Field_Displayed__c)
            {
                Member.MemberColumn mc = new Member.MemberColumn();
                mc.label = mdt.Field_Label__c;
                mc.type = mdt.Field_Type__c;
                mc.fieldName = mdt.Field_Name__c;
                memberColumns.add(mc);
            }
        }
        system.debug('memberColumns $$ ' + memberColumns);
        return memberColumns;
    }

    

}